### ISSUE TITLE
Cannot find module 'sleep'

### ISSUE THREAD

**Issue by n-patten** [H-s-O/tf2-botcheck#1]
Hey, we just met in that tf2 game. I tried downloading your repository and using it, but when I run botcheck.bat, I get an error reading "Cannot find module 'sleep'." I was wondering if there was an easy fix to this. Sorry if this is a dumb question. I've run install.bat and installed node js on my computer. Thanks!

**Comment by H-s-O** [comment]
Hello there!

From that error message, I suspect that during install, one of the module (`sleep`, which has a native addon) did not build properly.

If you open a command prompt and run the command `node --version`, what do you get? Also, did you install Node.js with the official installer and if so, did you select the option to install the necessary build tools?
![](https://www.osstuff.com/wp-content/uploads/2018/11/install-node-9.png)

**Comment by n-patten** [comment]
> 

That was it! Thanks so much!

I really love this. thanks so much for all of your hard work!

By the way, I think it would be awesome if this could loop while you're playing the game. I edited the botcheck.bat to do just that and I've found it so helpful.

Thanks again!
